spring.application.name=auth-service

server.port=8085

# PostgreSQL
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5436}/${DB_NAME:auth_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# RabbitMQ
spring.rabbitmq.addresses=${RABBITMQ_URL:amqp://admin:admin@localhost:5672}

# JWT Config
jwt.secret=${JWT_SECRET:supersecret2026}

# Observability (Reto 7)
management.endpoints.web.exposure.include=health,prometheus
management.endpoint.health.show-details=always
management.prometheus.metrics.export.enabled=true
# Logging & Tracing
management.tracing.enabled=true
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=${ZIPKIN_ENDPOINT:http://zipkin:9411/api/v2/spans}
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]

# Swagger UI Consistency
springdoc.swagger-ui.path=/api

logging.level.io.opentelemetry=TRACE
logging.level.io.opentelemetry.exporter.zipkin=TRACE
logging.level.org.springframework.boot.actuate.autoconfigure.tracing=TRACE
logging.level.org.springframework.web.filter.ServerHttpObservationFilter=TRACE
debug=true
