pipeline {
    agent any
    tools {
        nodejs 'NodeJS 20'
    }
    environment {
        SCANNER_HOME = tool 'SonarScanner'
    }
    stages {
        stage('Build') {
            steps {
                dir('employees-service') {
                    echo "Instalando dependencias y compilando..."
                    sh 'npm install'
                    sh 'npm run build'
                }
            }
        }
        stage('Test & Coverage') {
            steps {
                dir('employees-service') {
                    echo "Ejecutando pruebas y generando cobertura..."
                    sh 'npm run test:cov'
                }
            }
        }
        stage('SonarQube Analysis') {
            steps {
                dir('employees-service') {
                    withSonarQubeEnv('SonarQube') {
                        sh "${SCANNER_HOME}/bin/sonar-scanner"
                    }
                }
            }
        }
        stage('Quality Gate') {
            steps {
                timeout(time: 5, unit: 'MINUTES') {
                    // Requiere que el Webhook esté configurado en SonarQube hacia Jenkins
                    waitForQualityGate abortPipeline: true
                }
            }
        }
        stage('Package') {
            steps {
                dir('employees-service') {
                    script {
                        def imageName = "localhost:5000/employees-service"
                        def imageTag = "${env.BUILD_NUMBER}"
                        sh "docker build -t ${imageName}:${imageTag} -t ${imageName}:latest ."
                        sh "docker push ${imageName}:${imageTag}"
                        sh "docker push ${imageName}:latest"
                    }
                }
            }
        }
        stage('E2E Tests') {
            steps {
                echo "Corriendo pruebas E2E contra los servicios locales..."
                dir('e2e-tests') {
                    sh 'npm install'
                    sh 'npm test'
                }
            }
        }
    }
    post {
        success {
            echo "✅ Pipeline completado con éxito"
        }
        failure {
            echo "❌ Pipeline fallido"
        }
    }
}
