apiVersion: 1

contactPoints:
  - orgId: 1
    name: 'Email Alerts'
    receivers:
      - uid: email_webhook
        type: email
        settings:
          addresses: 'admin@empresa.com'

policies:
  - orgId: 1
    receiver: 'Email Alerts'
    group_by: ['alertname', 'service']
    repeat_interval: 1h
