sonar.projectKey=notifications-service
sonar.projectName=Notifications Service
sonar.sources=app
sonar.tests=app
sonar.test.inclusions=**/*_test.py,**/test_*.py
sonar.exclusions=**/test_*.py,**/*_test.py
sonar.python.coverage.reportPaths=coverage.xml
